# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: interviewed-db
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./dumps:/var/db_dumps
      - ./bin:/var/db_bin
      - postgres:/data/postgres

    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

  postgresclient:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.16
    restart: always
    ports:
      - "5050:80"
    volumes:
       - pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
volumes:
    postgres:
    pgadmin: